#Regularized Multi-Task Learning

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
data = load_breast_cancer()
# Preprocess the data
X = StandardScaler().fit_transform(data.data)
y = data.target
X = X[:50,:]

y[y == 0] = -1  # Convert labels to -1/+1
y=y[:50,]
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [ ]:
data = load_breast_cancer()

In [ ]:
X.shape

(50, 30)

In [ ]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For instance, field 0 is Mean Radius, field\n        10 is Radius SE, field 20 is Worst Radius.\n\n        - class:\n                - WDBC-Malignant\n                - WDBC-Benign\n\n    :Summary Statistics:\n\n    ===================================== ====== ======\n                                           Min    Max\n    ===================================== ====== ======\n    radius (mean):                        6.981  28.11\n    texture (mean):                       9.71   39.28\n    perimeter (mean):                     43.79  188.5\n    area (mean):                          143.5  2501.0\n    smoothness (mean):                    0.053  0.163\n    compactness (mean):                   0.019  0.345\n    concavity (mean):                     0.0    0.427\n    concave points (mean):                0.0    0.201\n    symmetry (mean):                      0.106  0.304\n    fractal dimension (mean):             0.05   0.097\n    radius (standard error):              0.112  2.873\n    texture (standard error):             0.36   4.885\n    perimeter (standard error):           0.757  21.98\n    area (standard error):                6.802  542.2\n    smoothness (standard error):          0.002  0.031\n    compactness (standard error):         0.002  0.135\n    concavity (standard error):           0.0    0.396\n    concave points (standard error):      0.0    0.053\n    symmetry (standard error):            0.008  0.079\n    fractal dimension (standard error):   0.001  0.03\n    radius (worst):                       7.93   36.04\n    texture (worst):                      12.02  49.54\n    perimeter (worst):                    50.41  251.2\n    area (worst):                         185.2  4254.0\n    smoothness (worst):                   0.071  0.223\n    compactness (worst):                  0.027  1.058\n    concavity (worst):                    0.0    1.252\n    concave points (worst):               0.0    0.291\n    symmetry (worst):                     0.156  0.664\n    fractal dimension (worst):            0.055  0.208\n    ===================================== ====== ======\n\n    :Missing Attribute Values: None\n\n    :Class Distribution: 212 - Malignant, 357 - Benign\n\n    :Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n    :Donor: Nick Street\n\n    :Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. topic:: References\n\n   - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction \n     for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on \n     Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n     San Jose, CA, 1993.\n   - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and \n     prognosis via linear programming. Operations Research, 43(4), pages 570-577, \n     July-August 1995.\n   - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n     to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994) \n     163-171.',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
import pandas as pd
data_df = pd.DataFrame(data = data.data,
                       columns = data.feature_names)
data_df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
data_df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
!pip install gurobipy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: gurobipy in /usr/local/lib/python3.10/dist-packages (10.0.1)

#The multi–task problem   to solving the following optimization problem:

In [ ]:
import gurobipy as gp
import numpy as np

m, n = X_train.shape
T = 1
lambda1 = 1.0
lambda2 = 1.0

# Create a Gurobi model
model = gp.Model()

# Create variables
w0 = model.addVar(name='w0')
v = model.addVars(T, n, name='v')
xi = model.addVars(m, T, name='xi')

# Add constraints
for i in range(m):
    for t in range(T):
        model.addConstr(y_train[i] * (w0 + gp.quicksum(v[t, j] * X_train[i, j] for j in range(n))) >= 1 - xi[i, t], name='constraint_1')
        model.addConstr(xi[i, t] >= 0, name='constraint_2')

# Add objective function
obj = (1/T) * gp.quicksum(v[t, j]**2 for t in range(T) for j in range(n)) + lambda2 * w0**2 + gp.quicksum(xi[i, t] for i in range(m) for t in range(T))
model.setObjective(obj, gp.GRB.MINIMIZE)
# Solve the model
model.optimize()
# Print the solution
print(f'Optimal objective value: {model.objVal:.4f}')
print(f'w0: {w0.x:.4f}')
w = np.array([v[t, j].x for j in range(n) for t in range(T)]).reshape(T, n)
print(f'w: {w}')

Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (linux64)

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 80 rows, 71 columns and 1320 nonzeros
Model fingerprint: 0x7f6efa07
Model has 31 quadratic objective terms
Coefficient statistics:
  Matrix range     [1e-03, 7e+00]
  Objective range  [1e+00, 1e+00]
  QObjective range [2e+00, 2e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 40 rows and 0 columns
Presolve time: 0.02s
Presolved: 40 rows, 71 columns, 1280 nonzeros
Presolved model has 31 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 7.800e+02
 Factor NZ  : 8.200e+02
 Factor Ops : 2.214e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   7.80109853e+06 -7.74909532e+06  2.22e+04 0.00e+00  1.00e+06     0s
   1   6.14351875e+05 -5.52793140e+05  2.73e+03 1.52e+02  1.58e+05     0s
   2   4.78229183e+05 -3.74803242e+05  0.00e+00 1.72e+01  2.75e+04     0s
   3   1.65248340e+05 -8.03255456e+04  0.00e+00 3.81e-01  2.62e+03     0s
   4   2.70405105e+04 -8.40374119e+03  0.00e+00 0.00e+00  3.22e+02     0s
   5   8.89811277e+03 -1.11340995e+03  0.00e+00 0.00e+00  9.02e+01     0s
   6   5.54592959e+02 -5.08658155e+01  0.00e+00 0.00e+00  5.45e+00     0s
   7   1.02593210e+02  1.55182455e+01  0.00e+00 4.61e-15  7.84e-01     0s
   8   3.31773840e+01  2.55706984e+01  0.00e+00 4.40e-15  6.85e-02     0s
   9   3.12580179e+01  3.04790658e+01  0.00e+00 6.57e-15  7.02e-03     0s
  10   3.09203681e+01  3.08802465e+01  0.00e+00 9.56e-15  3.61e-04     0s
  11   3.09091961e+01  3.09054010e+01  0.00e+00 7.28e-15  3.42e-05     0s
  12   3.09072000e+01  3.09071244e+01  0.00e+00 1.13e-14  6.82e-07     0s
  13   3.09071808e+01  3.09071729e+01  0.00e+00 5.32e-15  7.13e-08     0s
  14   3.09071796e+01  3.09071793e+01  0.00e+00 7.51e-15  3.00e-09     0s
  15   3.09071796e+01  3.09071796e+01  0.00e+00 4.25e-15  2.96e-12     0s

Barrier solved model in 15 iterations and 0.07 seconds (0.00 work units)
Optimal objective 3.09071796e+01

Optimal objective value: 30.9072
w0: 0.0000
w: [[1.04918949e-14 1.72176104e-14 9.70911495e-15 1.17171164e-14
  7.65549855e-15 5.68214699e-15 6.66021082e-15 6.59323191e-15
  7.74485460e-15 1.04579694e-14 8.49704775e-15 2.89043715e-01
  7.49826643e-15 1.09728816e-14 1.23354464e+00 8.06154972e-15
  1.39178601e-14 9.55788683e-15 2.43601525e-14 1.26086880e-14
  7.80653720e-15 1.11694077e-14 7.02398067e-15 8.57909671e-15
  6.32499287e-15 4.39842559e-15 5.20980902e-15 5.14238066e-15
  4.82086318e-15 4.80074040e-15]]

In [ ]:
w

array([[1.04918949e-14, 1.72176104e-14, 9.70911495e-15, 1.17171164e-14,
        7.65549855e-15, 5.68214699e-15, 6.66021082e-15, 6.59323191e-15,
        7.74485460e-15, 1.04579694e-14, 8.49704775e-15, 2.89043715e-01,
        7.49826643e-15, 1.09728816e-14, 1.23354464e+00, 8.06154972e-15,
        1.39178601e-14, 9.55788683e-15, 2.43601525e-14, 1.26086880e-14,
        7.80653720e-15, 1.11694077e-14, 7.02398067e-15, 8.57909671e-15,
        6.32499287e-15, 4.39842559e-15, 5.20980902e-15, 5.14238066e-15,
        4.82086318e-15, 4.80074040e-15]])

In [ ]:
y_pred = np.sign(X_test @ w.T + w0.x).T
accuracy = np.sum(y_pred == y_test)/y_pred.shape[1]
print(f'Test accuracy: {accuracy}')
print(y_pred)

Test accuracy: 0.6
[[ 1. -1. -1. -1. -1. -1. -1.  1.  1.  1.]]

In [ ]:
X.shape[0]

50

In [ ]:
import numpy as np
import gurobipy as gp
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load the dataset and preprocess the data
data = load_breast_cancer()
X = data.data
y = data.target
scaler = StandardScaler()
X = scaler.fit_transform(X)
X = X[:50,:]
y=y[:50,]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Set the parameters
m, n = X_train.shape
T = 1
rho1 = 1 / T * lambda1 * lambda2 / (lambda1 + lambda2)
rho2 = 1 / T * lambda1**2 / (lambda1 + lambda2)

# Define the optimization model
model = gp.Model()
w = {}
xi = {}
for t in range(T):
    w[t] = model.addVars(n, lb=-gp.GRB.INFINITY, name="w_"+str(t))
    xi[t] = model.addVars(m, lb=0, name="xi_"+str(t))
obj = gp.LinExpr()
for t in range(T):
    obj += gp.quicksum(xi[t][i] for i in range(m)) + rho1 * gp.quicksum(w[t][j]*w[t][j] for j in range(n)) + \
           rho2 * gp.quicksum((w[t][j] - 1/T * gp.quicksum(w[s][j] for s in range(T)))**2 for j in range(n))
model.setObjective(obj, gp.GRB.MINIMIZE)
for i in range(m):
    for t in range(T):
        model.addConstr(y_train[i]*gp.quicksum(X_train[i][j]*w[t][j] for j in range(n)) >= 1 - xi[t][i])
model.update()

# Solve the optimization model
model.optimize()

# Predict on the test set and calculate the accuracy
correct = 0
for i in range(X_test.shape[0]):
    pred = sum(X_test[i][j]*w[t][j].x for j in range(n) for t in range(T))
    if pred >= 0 and y_test[i] == 1:
        correct += 1
    elif pred < 0 and y_test[i] == 0:
        correct += 1
accuracy = correct / X_test.shape[0]
print("Accuracy:", accuracy)

Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (linux64)

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 40 rows, 70 columns and 160 nonzeros
Model fingerprint: 0x8bd320fc
Model has 30 quadratic objective terms
Coefficient statistics:
  Matrix range     [7e-03, 2e+00]
  Objective range  [1e+00, 1e+00]
  QObjective range [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 36 rows and 36 columns
Presolve time: 0.01s
Presolved: 4 rows, 34 columns, 124 nonzeros
Presolved model has 30 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 Free vars  : 30
 AA' NZ     : 6.000e+00
 Factor NZ  : 1.000e+01
 Factor Ops : 3.000e+01 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   7.03799998e+03  3.60000000e+01  0.00e+00 1.18e-06  1.00e+06     0s
   1   7.01324809e+03  3.47973796e+01  0.00e+00 1.58e-01  2.03e+03     0s
   2   2.08910052e+03  2.74245967e+01  0.00e+00 1.33e-15  2.58e+02     0s
   3   4.98215924e+01  2.81953565e+01  0.00e+00 2.22e-16  2.70e+00     0s
   4   3.83679151e+01  3.49744314e+01  0.00e+00 2.22e-16  4.24e-01     0s
   5   3.63626615e+01  3.59587048e+01  0.00e+00 1.11e-16  5.05e-02     0s
   6   3.61230408e+01  3.60775760e+01  0.00e+00 8.88e-16  5.68e-03     0s
   7   3.61033571e+01  3.60968867e+01  0.00e+00 1.11e-16  8.09e-04     0s
   8   3.61010104e+01  3.61004178e+01  0.00e+00 1.11e-16  7.41e-05     0s
   9   3.61009250e+01  3.61009101e+01  0.00e+00 2.22e-16  1.86e-06     0s
  10   3.61009244e+01  3.61009243e+01  0.00e+00 1.11e-16  1.85e-09     0s
  11   3.61009244e+01  3.61009244e+01  0.00e+00 2.78e-17  1.85e-12     0s

Barrier solved model in 11 iterations and 0.04 seconds (0.00 work units)
Optimal objective 3.61009244e+01

Accuracy: 1.0

In [ ]:
!pip install gurobipy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: gurobipy in /usr/local/lib/python3.10/dist-packages (10.0.1)

In [ ]:
import gurobipy as gp
from gurobipy import GRB
import numpy as np
from sklearn.datasets import load_breast_cancer

# Load the breast cancer dataset
data = load_breast_cancer()
X, y = data.data, data.target
X = X[:100,:]
y=y[:100,]

# Define the constants and kernel function
T = 1
lambda1 = 1
lambda2 = 1
C = T/(2*lambda1)
mu = T*lambda2/lambda1

def kernel(x, z, s, t):
    if s == t:
        return (1/mu + 1) * np.dot(x, z)
    else:
        return 1/mu * np.dot(x, z)

# Define the Gurobi model
model = gp.Model("svm_dual")

# Define the decision variables
alpha = {}
for i in range(X.shape[0]):
    for t in range(T):
        alpha[(i, t)] = model.addVar(lb=0, ub=C, name=f"alpha_{i}_{t}")

# Define the objective function
obj = gp.LinExpr()
for i in range(X.shape[0]):
    for t in range(T):
        obj += alpha[(i, t)]
        for j in range(X.shape[0]):
            for s in range(T):
                obj -= 0.5 * alpha[(i, s)] * y[i] * alpha[(j, t)] * y[j] * kernel(X[i], X[j], s, t)
model.setObjective(obj, GRB.MAXIMIZE)

# Define the constraints
for i in range(X.shape[0]):
    for t in range(T):
        expr = gp.LinExpr()
        for j in range(X.shape[0]):
            for s in range(T):
                expr += alpha[(j, s)] * y[j] * kernel(X[j], X[i], s, t)
        model.addConstr(alpha[(i, t)] >= 0, name=f"const_lb_{i}_{t}")
        model.addConstr(alpha[(i, t)] <= C, name=f"const_ub_{i}_{t}")

model.optimize()

# Extract the optimal solution
alpha_star = np.zeros((X.shape[0], T))
for i in range(X.shape[0]):
    for t in range(T):
        alpha_star[i, t] = alpha[(i, t)].x

# Define the function f_star
def f_star(x, t):
    result = 0
    for i in range(X.shape[0]):
        for s in range(T):
            result += alpha_star[i, s] * kernel(X[i], x, s, t)
    return result

# Compute the accuracy on the breast cancer dataset
y_pred = np.zeros(X.shape[0])
for i in range(X.shape[0]):
    scores = [f_star(X[i], t) for t in range(T)]
    y_pred[i] = np.sign(np.sum(scores))
accuracy = np.sum(y_pred == y)/len(y)

print(f"Accuracy on the breast cancer dataset: {accuracy:.4f}")

Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (linux64)

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 200 rows, 100 columns and 200 nonzeros
Model fingerprint: 0xf7753e39
Model has 630 quadratic objective terms
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  QObjective range [2e+05, 4e+06]
  Bounds range     [5e-01, 5e-01]
  RHS range        [5e-01, 5e-01]
Presolve removed 200 rows and 65 columns
Presolve time: 0.02s
Presolved: 0 rows, 35 columns, 0 nonzeros
Presolved model has 630 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 Free vars  : 29
 AA' NZ     : 4.060e+02
 Factor NZ  : 4.350e+02
 Factor Ops : 8.555e+03 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.70325015e+04  1.70412500e+04  2.71e+04 1.80e-05  1.00e+06     0s
   1   7.55938838e+01  1.70248997e+04  3.16e+01 2.09e-08  1.41e+03     0s
   2   2.54080111e+01  8.41335497e+03  2.21e+00 1.47e-09  1.82e+02     0s
   3   2.27513771e+01  6.77788708e+02  7.96e-02 5.28e-11  1.10e+01     0s
   4   3.16511416e+01  3.98716344e+01  1.51e-04 9.66e-13  1.21e-01     0s
   5   3.23643730e+01  3.26429637e+01  1.51e-10 6.93e-13  3.98e-03     0s
   6   3.24806318e+01  3.25216720e+01  1.51e-16 2.06e-13  5.86e-04     0s
   7   3.24972575e+01  3.25031229e+01  4.07e-20 1.06e-13  8.38e-05     0s
   8   3.24996198e+01  3.25004603e+01  1.69e-20 3.60e-14  1.20e-05     0s
   9   3.24999508e+01  3.25000710e+01  1.02e-20 1.38e-14  1.72e-06     0s
  10   3.24999955e+01  3.25000124e+01  5.08e-21 6.00e-15  2.42e-07     0s
  11   3.25000010e+01  3.25000031e+01  1.27e-21 2.44e-15  2.95e-08     0s
  12   3.25000022e+01  3.25000024e+01  1.69e-21 1.55e-15  2.56e-09     0s
  13   3.25000024e+01  3.25000024e+01  9.74e-21 1.33e-15  9.05e-12     0s

Barrier solved model in 13 iterations and 0.07 seconds (0.00 work units)
Optimal objective 3.25000024e+01

Accuracy on the breast cancer dataset: 0.3500

In [ ]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [ ]:
with open('multilabel_train_data.txt') as f:
    data_list = f.readlines()

In [ ]:
labels=[]
features=[]

for line in data_list:
  line_list=line.split(' ')
  labels.append(set(line_list[0].split(',')))
  for j in line_list[1:-1]:
    features.append(int(j.split(':')[0]))

features=np.array(features)
label_set=set([])
for i in labels:
  label_set=set.union(label_set,i)
label_arr=list(label_set)
labels_arr=np.array([int(label_arr[i]) for i in range(len(label_arr))])

features_arr=np.unique(features)
print('features are:',features_arr)
print('labels are:',labels_arr)

features are: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103]
labels are: [ 0  9  4  1  8 11  3 12  7  2 13  6 10  5]

In [ ]:
print('y Array: array of labels:\n')
labels_arr.sort()
print(labels_arr)
print('\n X array: array of features:\n')
print(features_arr)

y Array: array of labels:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]

 X array: array of features:

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103]

In [ ]:
print('Number of classes in dataset:',len(labels_arr),'\n')
print('Number of features in dataset:',len(features_arr),'\n')

Number of classes in dataset: 14

Number of features in dataset: 103

In [ ]:
# number of data points
n=len(data_list)
print('number of data points:',n)

number of data points: 1500

In [ ]:
#number of features
d=len(features_arr)
print('number of features:',d)

number of features: 103

In [ ]:
array=np.array([0.0 for i in range(n*(d))]).reshape(n,d)
array.shape

(1500, 103)

In [ ]:
labels=[]
for i in range(len(data_list)):
  line=data_list[i]
  line_list=line.split(' ')
  labels.append(set(line_list[0].split(',')))
  #print(i)
  for j in line_list[1:-1]:
    a=j.split(':')
    #print(a,int(a[0])-1,a[1])
    array[i,int(a[0])-1]=a[1]
len(array)

1500

In [ ]:
df=pd.DataFrame(array,columns=features_arr)
df

,1,2,3,4,5,6,7,8,9,10,...,94,95,96,97,98,99,100,101,102,103
0,-0.011858,-0.061636,0.054392,0.021137,0.089374,0.101825,-0.044525,0.222330,0.015575,-0.053591,...,-0.017531,-0.032930,-0.030487,0.009813,-0.002603,0.049288,-0.046913,-0.000844,0.004983,0.115765
1,-0.018183,-0.045645,0.002001,0.066467,-0.118108,0.105399,0.004705,0.046744,-0.060929,0.284897,...,0.033050,-0.159394,0.125488,-0.149774,-0.148373,0.135500,0.047781,0.079903,0.065097,-0.165039
2,0.074145,-0.044487,0.048191,-0.006614,0.042746,0.025960,0.021290,0.041714,0.048671,-0.038404,...,-0.099730,0.145222,-0.102574,0.143100,0.135860,-0.098214,-0.104915,-0.085630,0.174316,-0.022570
3,0.044432,-0.007842,0.018440,0.036639,0.243409,0.154859,0.128655,0.122329,0.004179,0.106768,...,-0.053067,0.011885,-0.052333,-0.056184,-0.056243,-0.049476,-0.056670,0.120910,-0.028053,0.086152
4,0.051570,-0.016571,0.014702,0.024296,0.155760,0.048347,-0.031283,0.133782,0.085081,-0.047716,...,-0.107924,-0.086031,-0.098521,-0.086622,-0.091729,0.210266,0.110243,0.140546,0.182154,-0.101904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,-0.116754,-0.017859,-0.051158,0.015938,0.015013,0.121055,-0.099059,0.023402,0.005873,0.019754,...,0.057323,-0.125292,0.177598,-0.127144,-0.126141,0.046453,-0.070558,0.138768,-0.039471,-0.016383
1496,0.085234,0.049690,0.134850,0.091247,0.239547,0.140304,0.166942,0.050181,0.126451,0.135792,...,-0.046560,0.071134,-0.041950,0.076210,0.077935,-0.040123,-0.056090,-0.052238,-0.020390,0.085778
1497,0.074028,0.014501,-0.041893,0.030209,-0.061547,0.022142,-0.022888,0.023375,0.073267,0.019675,...,-0.064247,0.158470,-0.061079,0.188122,0.182037,-0.056295,-0.075996,-0.072424,-0.039109,0.019538
1498,-0.058193,0.502205,-0.081411,-0.033651,0.001250,0.086514,-0.005469,0.033748,0.007124,-0.044017,...,-0.054680,-0.000601,-0.050850,-0.038719,0.178632,0.151786,-0.062065,-0.017584,0.498207,-0.072177
1499,-0.128468,-0.003593,0.039187,0.032379,-0.006359,-0.049659,-0.147537,-0.092815,0.050572,0.001716,...,-0.020853,-0.044238,-0.065766,-0.062276,-0.069627,-0.010034,0.086035,-0.062728,-0.048271,-0.124432

In [ ]:
df['labels']=labels

In [ ]:
df

,1,2,3,4,5,6,7,8,9,10,...,95,96,97,98,99,100,101,102,103,labels
0,-0.011858,-0.061636,0.054392,0.021137,0.089374,0.101825,-0.044525,0.222330,0.015575,-0.053591,...,-0.032930,-0.030487,0.009813,-0.002603,0.049288,-0.046913,-0.000844,0.004983,0.115765,"{12, 6, 11, 7}"
1,-0.018183,-0.045645,0.002001,0.066467,-0.118108,0.105399,0.004705,0.046744,-0.060929,0.284897,...,-0.159394,0.125488,-0.149774,-0.148373,0.135500,0.047781,0.079903,0.065097,-0.165039,"{4, 12, 3, 11}"
2,0.074145,-0.044487,0.048191,-0.006614,0.042746,0.025960,0.021290,0.041714,0.048671,-0.038404,...,0.145222,-0.102574,0.143100,0.135860,-0.098214,-0.104915,-0.085630,0.174316,-0.022570,"{6, 4, 11, 7, 12, 5, 10}"
3,0.044432,-0.007842,0.018440,0.036639,0.243409,0.154859,0.128655,0.122329,0.004179,0.106768,...,0.011885,-0.052333,-0.056184,-0.056243,-0.049476,-0.056670,0.120910,-0.028053,0.086152,"{2, 10, 9, 1}"
4,0.051570,-0.016571,0.014702,0.024296,0.155760,0.048347,-0.031283,0.133782,0.085081,-0.047716,...,-0.086031,-0.098521,-0.086622,-0.091729,0.210266,0.110243,0.140546,0.182154,-0.101904,"{2, 12, 1, 11}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,-0.116754,-0.017859,-0.051158,0.015938,0.015013,0.121055,-0.099059,0.023402,0.005873,0.019754,...,-0.125292,0.177598,-0.127144,-0.126141,0.046453,-0.070558,0.138768,-0.039471,-0.016383,"{0, 12, 1, 11}"
1496,0.085234,0.049690,0.134850,0.091247,0.239547,0.140304,0.166942,0.050181,0.126451,0.135792,...,0.071134,-0.041950,0.076210,0.077935,-0.040123,-0.056090,-0.052238,-0.020390,0.085778,"{4, 12, 3, 11}"
1497,0.074028,0.014501,-0.041893,0.030209,-0.061547,0.022142,-0.022888,0.023375,0.073267,0.019675,...,0.158470,-0.061079,0.188122,0.182037,-0.056295,-0.075996,-0.072424,-0.039109,0.019538,"{4, 12, 3, 11}"
1498,-0.058193,0.502205,-0.081411,-0.033651,0.001250,0.086514,-0.005469,0.033748,0.007124,-0.044017,...,-0.000601,-0.050850,-0.038719,0.178632,0.151786,-0.062065,-0.017584,0.498207,-0.072177,"{8, 7}"
1499,-0.128468,-0.003593,0.039187,0.032379,-0.006359,-0.049659,-0.147537,-0.092815,0.050572,0.001716,...,-0.044238,-0.065766,-0.062276,-0.069627,-0.010034,0.086035,-0.062728,-0.048271,-0.124432,"{10, 12, 9, 11}"

In [ ]:
labels_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
# number of labels
k=len(labels_arr)
print('number of distinct classes',k)

number of distinct classes 14

In [ ]:
label_matrix=np.array([0 for i in range(n*k)]).reshape((n,k))
for i in range(n):
  for l in range(len(labels_arr)):
    if str(labels_arr[l]) in df.labels[i]:
      label_matrix[i][l]=1
    else:
      label_matrix[i][l]=-1
print(label_matrix.shape)

(1500, 14)

In [ ]:
def lab(x,i):
  if str(i) in x:
    return 1
  else:
    return -1

In [ ]:
labels_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
for i in labels_arr:
  df[f'labels_{i}']=df['labels'].apply(lambda x: lab(x,i))

In [ ]:
df

,1,2,3,4,5,6,7,8,9,10,...,labels_4,labels_5,labels_6,labels_7,labels_8,labels_9,labels_10,labels_11,labels_12,labels_13
0,-0.011858,-0.061636,0.054392,0.021137,0.089374,0.101825,-0.044525,0.222330,0.015575,-0.053591,...,-1,-1,1,1,-1,-1,-1,1,1,-1
1,-0.018183,-0.045645,0.002001,0.066467,-0.118108,0.105399,0.004705,0.046744,-0.060929,0.284897,...,1,-1,-1,-1,-1,-1,-1,1,1,-1
2,0.074145,-0.044487,0.048191,-0.006614,0.042746,0.025960,0.021290,0.041714,0.048671,-0.038404,...,1,1,1,1,-1,-1,1,1,1,-1
3,0.044432,-0.007842,0.018440,0.036639,0.243409,0.154859,0.128655,0.122329,0.004179,0.106768,...,-1,-1,-1,-1,-1,1,1,-1,-1,-1
4,0.051570,-0.016571,0.014702,0.024296,0.155760,0.048347,-0.031283,0.133782,0.085081,-0.047716,...,-1,-1,-1,-1,-1,-1,-1,1,1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,-0.116754,-0.017859,-0.051158,0.015938,0.015013,0.121055,-0.099059,0.023402,0.005873,0.019754,...,-1,-1,-1,-1,-1,-1,-1,1,1,-1
1496,0.085234,0.049690,0.134850,0.091247,0.239547,0.140304,0.166942,0.050181,0.126451,0.135792,...,1,-1,-1,-1,-1,-1,-1,1,1,-1
1497,0.074028,0.014501,-0.041893,0.030209,-0.061547,0.022142,-0.022888,0.023375,0.073267,0.019675,...,1,-1,-1,-1,-1,-1,-1,1,1,-1
1498,-0.058193,0.502205,-0.081411,-0.033651,0.001250,0.086514,-0.005469,0.033748,0.007124,-0.044017,...,-1,-1,-1,1,1,-1,-1,-1,-1,-1
1499,-0.128468,-0.003593,0.039187,0.032379,-0.006359,-0.049659,-0.147537,-0.092815,0.050572,0.001716,...,-1,-1,-1,-1,-1,1,1,1,1,-1

In [ ]:
df['labels']

0                 {12, 6, 11, 7}
1                 {4, 12, 3, 11}
2       {6, 4, 11, 7, 12, 5, 10}
3                  {2, 10, 9, 1}
4                 {2, 12, 1, 11}
                  ...
1495              {0, 12, 1, 11}
1496              {4, 12, 3, 11}
1497              {4, 12, 3, 11}
1498                      {8, 7}
1499             {10, 12, 9, 11}
Name: labels, Length: 1500, dtype: object

In [ ]:
df.iloc[:,:-14]

,1,2,3,4,5,6,7,8,9,10,...,95,96,97,98,99,100,101,102,103,labels
0,-0.011858,-0.061636,0.054392,0.021137,0.089374,0.101825,-0.044525,0.222330,0.015575,-0.053591,...,-0.032930,-0.030487,0.009813,-0.002603,0.049288,-0.046913,-0.000844,0.004983,0.115765,"{12, 6, 11, 7}"
1,-0.018183,-0.045645,0.002001,0.066467,-0.118108,0.105399,0.004705,0.046744,-0.060929,0.284897,...,-0.159394,0.125488,-0.149774,-0.148373,0.135500,0.047781,0.079903,0.065097,-0.165039,"{4, 12, 3, 11}"
2,0.074145,-0.044487,0.048191,-0.006614,0.042746,0.025960,0.021290,0.041714,0.048671,-0.038404,...,0.145222,-0.102574,0.143100,0.135860,-0.098214,-0.104915,-0.085630,0.174316,-0.022570,"{6, 4, 11, 7, 12, 5, 10}"
3,0.044432,-0.007842,0.018440,0.036639,0.243409,0.154859,0.128655,0.122329,0.004179,0.106768,...,0.011885,-0.052333,-0.056184,-0.056243,-0.049476,-0.056670,0.120910,-0.028053,0.086152,"{2, 10, 9, 1}"
4,0.051570,-0.016571,0.014702,0.024296,0.155760,0.048347,-0.031283,0.133782,0.085081,-0.047716,...,-0.086031,-0.098521,-0.086622,-0.091729,0.210266,0.110243,0.140546,0.182154,-0.101904,"{2, 12, 1, 11}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,-0.116754,-0.017859,-0.051158,0.015938,0.015013,0.121055,-0.099059,0.023402,0.005873,0.019754,...,-0.125292,0.177598,-0.127144,-0.126141,0.046453,-0.070558,0.138768,-0.039471,-0.016383,"{0, 12, 1, 11}"
1496,0.085234,0.049690,0.134850,0.091247,0.239547,0.140304,0.166942,0.050181,0.126451,0.135792,...,0.071134,-0.041950,0.076210,0.077935,-0.040123,-0.056090,-0.052238,-0.020390,0.085778,"{4, 12, 3, 11}"
1497,0.074028,0.014501,-0.041893,0.030209,-0.061547,0.022142,-0.022888,0.023375,0.073267,0.019675,...,0.158470,-0.061079,0.188122,0.182037,-0.056295,-0.075996,-0.072424,-0.039109,0.019538,"{4, 12, 3, 11}"
1498,-0.058193,0.502205,-0.081411,-0.033651,0.001250,0.086514,-0.005469,0.033748,0.007124,-0.044017,...,-0.000601,-0.050850,-0.038719,0.178632,0.151786,-0.062065,-0.017584,0.498207,-0.072177,"{8, 7}"
1499,-0.128468,-0.003593,0.039187,0.032379,-0.006359,-0.049659,-0.147537,-0.092815,0.050572,0.001716,...,-0.044238,-0.065766,-0.062276,-0.069627,-0.010034,0.086035,-0.062728,-0.048271,-0.124432,"{10, 12, 9, 11}"

In [ ]:
x=df.iloc[:,:-15].to_numpy()
y=df.iloc[:,-14:].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score

class MultiLabelAdaBoost:
    """
    Multi-label AdaBoost implementation.
    """
    def __init__(self, T=50, base_estimator=DecisionTreeClassifier(max_depth=1)):
        self.T = T
        self.base_estimator = base_estimator
        self.estimators_ = []
        self.estimator_weights_ = np.zeros(T)
        self.estimator_errors_ = np.zeros(T)
        self.sample_weights = []

    def fit(self, X, Y):
        n_samples, n_features = X.shape
        self.sample_weights = np.zeros(n_samples) + 1/n_samples
        Y = pd.get_dummies(Y.apply(pd.Series).stack(), prefix='label').sum(level=0, axis=1)
        for t in range(self.T):
            estimator = self.base_estimator.fit(X, Y, sample_weight=self.sample_weights)
            self.estimators_.append(estimator)
            Y_pred = estimator.predict(X)
            error = np.sum(self.sample_weights*(1-(Y == Y_pred)).sum(axis=1))/np.sum(self.sample_weights)
            self.estimator_errors_[t] = error
            if error >= 0.5:
                break
            alpha = np.log((1-error)/error)
            self.estimator_weights_[t] = alpha
            self.sample_weights *= np.exp(alpha*(1-(Y == Y_pred)).sum(axis=1))
            self.sample_weights /= np.sum(self.sample_weights)
        self.estimator_weights_ = self.estimator_weights_[:t+1]
        self.estimators_ = self.estimators_[:t+1]
        self.estimator_errors_ = self.estimator_errors_[:t+1]
        return self

    def predict(self, X):
        Y_pred = np.zeros((X.shape[0], len(self.estimators_)))
        for t, estimator in enumerate(self.estimators_):
            Y_pred_t = estimator.predict(X)
            Y_pred[Y_pred_t, t] = self.estimator_weights_[t]
        Y_pred = (Y_pred/Y_pred.sum(axis=1)[:, None]).dot(self.estimators_[-1].classes_)
        return Y_pred

# def load_data(file_path):
#     data = pd.read_csv(file_path, header=None)
#     X = pd.DataFrame([list(map(float, sample.split(' ')[1:])) for sample in data[0]])
#     Y = data[0].apply(lambda x: list(map(int, x.split(' ')[0].split(','))))
#     return X, Y

# if __name__ == '__main__':
#     # Load data
#     X_train, Y_train = load_data('multilabel_train_data.txt')
#     X_test, Y_test = load_data('sample_multilabel_test_data.txt')

    # Train model
model = MultiLabelAdaBoost(T=50, base_estimator=DecisionTreeClassifier(max_depth=1))

model.fit(X_train, y_train)

    # Predict on test data

Y_test_pred = model.predict(X_test)

    # Compute accuracy and F1 score
accuracy = accuracy_score(y_test, y_test_pred.round(), normalize=True)

f1 = f1_score(y_test, y_test_pred.round(), average='weighted')
print(f"Accuracy: {accuracy:.3f}")

print(f"F1 score: {f1:.3f}")

AttributeError: ignored

In [ ]:
x=df.iloc[:,:-15].to_numpy()
y=df.iloc[:,-14:].to_numpy()
X = x[:100,:]
y=y[:100,]
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

# Define the constants and kernel function
T = 14
lambda1 = 1
lambda2 = 1
C = T/(2*lambda1)
mu = T*lambda2/lambda1

def kernel(x, z, s, t):
    if s == t:
        return (1/mu + 1) * np.dot(x, z)
    else:
        return 1/mu * np.dot(x, z)

# Define the Gurobi model
model = gp.Model("svm_dual")

# Define the decision variables
alpha = {}
for i in range(X.shape[0]):
    for t in range(T):
        alpha[(i, t)] = model.addVar(lb=0, ub=C, name=f"alpha_{i}_{t}")

# Define the objective function
obj = gp.LinExpr()
for i in range(X.shape[0]):
    for t in range(T):
        obj += alpha[(i, t)]
        for j in range(X.shape[0]):
            for s in range(T):
                obj -= 0.5 * alpha[(i, s)] * y[i] * alpha[(j, t)] * y[j] * kernel(X[i], X[j], s, t)
model.setObjective(obj, GRB.MAXIMIZE)

# Define the constraints
for i in range(X.shape[0]):
    for t in range(T):
        expr = gp.LinExpr()
        for j in range(X.shape[0]):
            for s in range(T):
                expr += alpha[(j, s)] * y[j] * kernel(X[j], X[i], s, t)
        model.addConstr(alpha[(i, t)] >= 0, name=f"const_lb_{i}_{t}")
        model.addConstr(alpha[(i, t)] <= C, name=f"const_ub_{i}_{t}")
model.optimize()

# Extract the optimal solution
alpha_star = np.zeros((X.shape[0], T))
for i in range(X.shape[0]):
    for t in range(T):
        alpha_star[i, t] = alpha[(i, t)].x

# Define the function f_star
def f_star(x, t):
    result = 0
    for i in range(X.shape[0]):
        for s in range(T):
            result += alpha_star[i, s] * kernel(X[i], x, s, t)
    return result
y_pred = np.zeros(X.shape[0])
for i in range(X.shape[0]):
    scores = [f_star(X[i], t) for t in range(T)]
    y_pred[i] = np.sign(np.sum(scores))
accuracy = np.sum(y_pred == y)/len(y)

print(f"Accuracy:, {accuracy:.4f}")

In [ ]:
x=df.iloc[:,:-15].t0_numpy()

In [ ]:
y=df.iloc[:,-14:].to_numpy()

In [ ]:
df.iloc[:,-14:]

In [ ]:
df.iloc[:,-14:].shape

In [ ]:
# Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Define the SVM model for single-task learning
svm = SVC(kernel='linear', C=1, probability=True)

# Fit the model to the training data
for i in range(0,14):
    svm.fit(X_train, y_train[:,i])
# Evaluate the model on the testing data
#score = svm.score(X_test, y_test)
t_scores = []
for i in range(14):
    t_scores.append(svm.score(X_test,y_test[:,i]))
t_mean_score = sum(t_scores) / len(t_scores)
print(f"T separate SVMs mean accuracy: {t_mean_score:.3f}")
print('Accuracy:', score)

In [ ]:
import matplotlib.pyplot as plt

# Define data for bar chart
task_labels = ['Single-Task SVM', 'Multi-Task SVM']
task_scores = [score, multi_task_svm.score(X_test, y_test)]

# Create bar chart
fig = plt.figure(figsize=(10, 5))
plt.bar(task_labels, task_scores, color=['blue', 'orange'])
plt.title('Comparison of Single-Task and Multi-Task SVM on')
plt.xlabel('Approach')
plt.ylabel('Accuracy')
plt.show()

In [ ]:
plt.plot(task_labels, task_scores)